name: A TO A:GH_PAGES
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: tassiofront/test-ghpages-deploy
          TARGET_BRANCH: main
          BUILD_SCRIPT: npm i && npm run build:docs
          BUILD_DIR: docs/.vuepress/dist/
